### DISCUSSION TITLE
Separating comment blocks from a source file

### DISCUSSION THREAD

**Discussion by kikugie** [antlr/antlr4#4831] [Q&A]
My goal is to process comment contents of a file, while preserving the rest. For example in a given file:
```java
public class Example {
    public static void main(String[] args) {
        /*Nothing yet*/
    }
}
```

The parser should split it in the following structure:
```yml
file:
  content: "public class Example {\n    public static void main(String[] args) {\n        "
  comment:
    opener: "/*"
    body: "Nothing yet"
    closer: "*/"
  content: "\n    }\n}"
```

The ANTLR documentation goes into escaping comments, however in this case they must be preserved, and it seems like the concept of "match everything, but ..." is not straightforward *(+ of course dealing with fake comments inside strings is a hassle)*.
How would I go about making grammar that accomplishes this?

In my case I'm making a file preprocessor that uses simple code snippets inside comments that are ignored by the underlying language, but instead evaluated by the preprocessor. Since from the perspective of the processor the underlying language is just text, I parse the content in two passes:
1. Separate comments from code content: https://codeberg.org/stonecutter/stonecutter/src/branch/0.6/stitcher/src/main/kotlin/dev/kikugie/stitcher/scanner/Scanner.kt
2. Process relevant comments individually: https://codeberg.org/stonecutter/stonecutter/src/branch/0.6/stitcher/src/main/kotlin/dev/kikugie/stitcher/parser/CommentParser.kt

I would like to use ANTLR with this separation, so the parser for the first pass can be swapped for different file formats, allowing the second pass parser to work on the same structure.
